[workspace]

[package]
name = "cockatiel-stress-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cockatiel-proto = { git = "https://github.com/vulbyte/cockatiel_proto", rev = "881c4bfd3396007127ac9196d90c304035c078ce" }
tokio = { version = "1.38", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["rustls-tls-webpki-roots"] }
rustls = "0.23"
rustls-pemfile = "2"
futures-util = "0.3"
prost = "0.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v7", "v4"] }
